dir_input: images/
dir_output: images/
input_exr_ext: .exr
output_mask_ext: .segments.png
output_mask_rgb_ext: .segments_rgb.png  # RGB visualization of output masks
id_map_ext: .id_map.json  # Output files with mapping from object names to IDs in mask.
random_seed: 0  # The colors for RGB visualization are generated randomly. This fixes order of random colors.
